[build]
  Command = "yarn build"
  Publish = "build"

[build.environment]
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true # Ensure that we always redirect
